name = "linkupcraft-07-2026"
author = "CreatorFactorem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a86e3bace1918bd456eac54d8d517319cec2653d8226800433a47498ffaad8e"

[versions]
fabric = "0.19.3"
minecraft = "1.21.9"
