name = "linkupcraft-07-2026"
author = "CreatorFactorem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c15f7837f1caa02c9718d8cb91d72be6dcad66af93f5823c29ef99252e9b676d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
