name = "linkupcraft-07-2026"
author = "CreatorFactorem"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d4c39818f958faa64793b901bc0dd9d72b08e1959cc4d98b33401c4f13323505"

[versions]
fabric = "0.19.3"
minecraft = "1.21.9"
